version: '3.4'
services:
  proxy:
    image: homeassistant/homeassistant
    networks:
    - proxy
    deploy:
      replicas: 1
      labels:
      - traefik.enabled=true
      - traefik.http.services.hass.loadbalancer.server.port=8123
      - "traefik.http.routers.hass.rule=Host(`hass.${DOCKER_DOMAIN}`) || PathPrefixStrip: /hass"
      - traefik.http.routers.hass.entrypoints=http
      placement:
        constraints:
        - node.role == manager
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: ${LOGGING_DRIVER:?not set}
networks:
  proxy:
    external: true
volumes:
  homeassistant_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.19.181.254,v3,nolock,soft,rw
      device: ":${HOMEASSISTANT_NFS_DIR:?not set}"
