#cloud-config

hostname: controller
manage_etc_hosts: true

users:
  - name: USERNAME
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,docker,netdev,video
    lock_passwd: true

package_update: true
package_upgrade: false
package_reboot_if_required: true

packages:
 - ssh-import-id
 - bridge-utils
 - wiringpi
 - python-rpi.gpio
 - minicom
 - python-smbus
 - nfs-common
 - nfs-server

locale: "en_US.UTF-8"
timezone: "UTC"

# These commands will be ran once on first boot only
runcmd:
  - 'systemctl enable github-keys@USERNAME.timer'
  - 'mv /etc/network/interfaces.controller /etc/network/interfaces'
  - 'cat /etc/dhcpcd.conf.controller >> /etc/dhcpcd.conf'
  - 'systemctl enable .timer'
  - "echo 'iptables-persistent iptables-persistent/autosave_v4 boolean false' | debconf-set-selections"
  - "echo 'iptables-persistent iptables-persistent/autosave_v6 boolean false' | debconf-set-selections"
  - 'apt-get install -y iptables-persistent'
  - [sed, -i, "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/", /etc/sysctl.conf]
  - 'echo "172.19.181.1 p1" >> /etc/hosts'
  - 'echo "172.19.181.2 p2" >> /etc/hosts'
  - 'echo "172.19.181.3 p3" >> /etc/hosts'
  - 'echo "172.19.181.4 p4" >> /etc/hosts'
  - docker swarm init --advertise-addr 172.19.181.254
  - mkdir /nfs
  - exportfs

write_files:
  - content: |
      [Unit]
      Description=Import keys on boot and keep updated
      [Timer]
      OnBootSec=1min
      OnUnitActiveSec=1d
      [Install]
      WantedBy=timers.target
    path: /etc/systemd/system/github-keys@.timer
  - content: |
      [Unit]
      Description=Import keys for %i
      Wants=network-online.target
      After=network-online.target
      [Service]
      Type=oneshot
      ExecStart=/usr/bin/ssh-import-id gh:%i
      User=%i
    path: /etc/systemd/system/github-keys@.service
  # Controller
  - content: |
      [Unit]
      Description=Turn on clusterhat
      [Timer]
      OnBootSec=1min
      [Install]
      WantedBy=timers.target
    path: /etc/systemd/system/clusterhat.timer
  - content: |
      [Unit]
      Description=Turn on clusterhat
      Wants=network-online.target
      After=network-online.target
      [Service]
      Type=oneshot
      ExecStart=/sbin/clusterhat on
    path: /etc/systemd/system/clusterhat.service
  ## Content to show on login console
  - content: |
      HypriotOS (Debian GNU/Linux 9) \n \l
      br0 - IPv4: \4{br0} IPv6: \6{br0}
      eth0 - IPv4: \4{eth0} IPv6: \6{eth0}
    path: /etc/issue
  ### Scripts
  - content: UDEV_RULES
    encoding: b64
    path: /etc/udev/rules.d/90-clusterhat.rules
  - content: CLUSTERHAT
    encoding: b64
    permissions: '0755'
    owner: root:root
    path: /sbin/clusterhat
  - content: XRA_SCRIPT
    encoding: b64
    owner: root:root
    path: /usr/share/clusterhat/python/xra1200.py
  - content: INTERFACES
    encoding: b64
    path: /etc/network/interfaces.d/clusterhat

  ### Interfaces
  - content: |
      # interfaces(5) file used by ifup(8) and ifdown(8)
      # Include files from /etc/network/interfaces.d:
      source-directory /etc/network/interfaces.d
      auto br0
      iface br0 inet manual
          bridge_ports none
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
    path: /etc/network/interfaces.controller
    
  - content: |
      # ClusterHAT
      interface eth0
      static ip_address=STATIC_IP_ADDR/24
      static routers=LAN_ROUTER
      static domain_name_servers=LAN_ROUTER 1.1.1.1

      denyinterfaces ethpi1 ethpi2 ethpi3 ethpi4
      profile clusterhat_fallback_usb0
      static routers=172.19.181.254
      static domain_name_servers=LAN_ROUTER 1.1.1.1

      profile clusterhat_fallback_br0
      static ip_address=172.19.181.254/24

      interface usb0
      fallback clusterhat_fallback_usb0

      interface br0
      fallback clusterhat_fallback_br0
    path: /etc/dhcpcd.conf.controller
  - content: |
      i2c-dev
    path: /etc/modules

  - content: |
      # Generated by iptables-save v1.6.0 on Fri Mar 13 00:00:00 2018
      *filter
      :INPUT ACCEPT [7:1365]
      :FORWARD ACCEPT [0:0]
      :OUTPUT ACCEPT [0:0]
      -A FORWARD -i br0 ! -o br0 -j ACCEPT
      -A FORWARD -o br0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      COMMIT
      # Completed on Fri Mar 13 00:00:00 2018
      # Generated by iptables-save v1.6.0 on Fri Mar 13 00:00:00 2018
      *nat
      :PREROUTING ACCEPT [8:1421]
      :INPUT ACCEPT [7:1226]
      :OUTPUT ACCEPT [0:0]
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING -s 172.19.181.0/24 ! -o br0 -j MASQUERADE
      COMMIT
      # Completed on Fri Mar 13 00:00:00 2018
    path: /etc/iptables/rules.v4

  ## Connection over serial - minicom pX
  - content: |
      pu port             /dev/ttypi1
    path: /etc/minicom/minirc.p1

  - content: |
      pu port             /dev/ttypi2
    path: /etc/minicom/minirc.p2

  - content: |
      pu port             /dev/ttypi3
    path: /etc/minicom/minirc.p3

  - content: |
      pu port             /dev/ttypi4
    path: /etc/minicom/minirc.p4

  ## NFS
  - content: |
      /nfs 172.19.181.0/24(rw,sync) 192.168.1.30(rw,sync)
    path: /etc/exports

power_state:
  delay: now
  mode: reboot
  message: rebooting...
  timeout: 5
  condition: true