version: '3.4'
services:
  proxy:
    image: traefik
    command:
    - "--api"
    - "--entrypoints.http.address=:80"
    - "--entrypoints.https.address=:443"
    - "--entrypoints.mqtts.address=:8883"
    - "--providers.docker"
    - "--providers.docker.exposedByDefault=false"
    - "--providers.docker.network=proxy"
    - "--providers.docker.swarmmode"
    - "--providers.docker.watch"
    - "--certificatesResolvers.le.acme.email=${SMTP_EMAIL}"
    - "--certificatesResolvers.le.acme.storage=/etc/traefik/acme/acme.json"
    # used during the challenge
    - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=http"
    - "--metrics=true"
    - "--metrics.prometheus=true"
    - "--metrics.prometheus.entryPoint=https"
    - "--accesslog=true"
    ports:
    - 80:80
    - 443:443
    - 8883:8883
    networks:
    - proxy
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "traefik_certs:/etc/traefik/acme"
    deploy:
      mode: global
      labels:
      - traefik.enable=true
      # Global Redirect to HTTPS
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      - "traefik.http.routers.api.rule=Host(`proxy.${SUBDOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.tls.certresolver=le"
      - "traefik.http.routers.api.middlewares=auth-proxy"
      - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.auth-proxy.basicauth.users=${TRAEFIK_PROXY_CREDENTIALS}"
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
    logging:
      driver: ${LOGGING_DRIVER:?not set}
networks:
  proxy:
    external: true
volumes:
  traefik_certs:
