version: '3.4'
services:
  ui:
    image: grafana/grafana:6.5.2
    environment:
    - GF_ANALYTICS_ENABLED=false
    - GF_REPORTING_ENABLED=false
    - GF_DASHBOARDS_VERSIONS_TO_KEEP=5
    - GF_SMTP_ENABLED=true
    - GF_SMTP_HOST__FILE=/run/secrets/smtp_host
    - GF_SMTP_USER__FILE=/run/secrets/smtp_user
    - GF_SMTP_PASSWORD__FILE=/run/secrets/smtp_password
    - GF_SMTP_FROM_ADDRESS__FILE=/run/secrets/smtp_from_address
    - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s
    - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/admin_user
    - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/admin_password
    - GF_INSTALL_PLUGINS=blackmirror1-singlestat-math-panel,grafana-piechart-panel
    volumes:
    - grafana:/var/lib/grafana
    secrets:
    - source: grafana_admin_user.v1
      target: admin_user
    - source: grafana_admin_password.v1
      target: admin_password
    - source: grafana_smtp_host.v1
      target: smtp_host
    - source: grafana_smtp_user.v1
      target: smtp_user
    - source: grafana_smtp_password.v1
      target: smtp_password
    - source: grafana_smtp_from_address.v1
      target: smtp_from_address
    networks:
    - proxy
    - database
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.rule=Host(`grafana.${SUBDOMAIN}`)
      - traefik.http.routers.grafana.entrypoints=https
      - traefik.http.routers.grafana.tls=true
    logging:
      driver: ${LOGGING_DRIVER:?not set}
secrets:
  grafana_admin_user.v1:
    file: ./secrets/grafana_admin_user
  grafana_admin_password.v1:
    file: ./secrets/grafana_admin_password
  grafana_smtp_host.v1:
    file: ./secrets/smtp_host
  grafana_smtp_user.v1:
    file: ./secrets/smtp_email
  grafana_smtp_password.v1:
    file: ./secrets/smtp_password
  grafana_smtp_from_address.v1:
    file: ./secrets/smtp_email
volumes:
  grafana:
networks:
  proxy:
    external: true
  database:
    external: true

