version: '3.4'
services:
  telegraf:
    image: telegraf:latest
    configs:
    - source: config.v2
      target: /etc/telegraf/telegraf.conf
    networks:
    - database
    environment:
      MQTT_USERNAME: ${MQTT_USERNAME:?err}
      MQTT_PASSWORD: ${MQTT_PASSWORD:?err}
      INFLUXDB_TELEGRAF_USER: ${INFLUXDB_TELEGRAF_USER:?err}
      INFLUXDB_TELEGRAF_PASSWORD: ${INFLUXDB_TELEGRAF_PASSWORD:?err}
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
        - node.role == manager
    logging:
      driver: ${LOGGING_DRIVER:?not set}
configs:
  config.v2:
    file: ./configs/telegraf.conf
networks:
  database:
    external: true