version: '3.5'
services:
  hass:
    image: homeassistant/home-assistant:stable
    networks:
    - proxy
    volumes:
    - ./data/homeassistant:/config
    healthcheck:
      test: curl -f http://localhost:8123 || exit 1
      interval: 30s
      timeout: 10s
      retries: 6
    deploy:
      replicas: 1
      labels:
      - traefik.enable=true
      - traefik.http.services.hass.loadbalancer.server.port=8123
      - traefik.http.routers.hass.rule=Host(`hass.${SUBDOMAIN}`)
      - traefik.http.routers.hass.entrypoints=https
      - traefik.http.routers.hass.tls=true
      placement:
        constraints:
        - node.role == manager
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: ${LOGGING_DRIVER:?not set}
networks:
  proxy:
    external: true
