version: '3.4'
services:
  influxdb:
    image: influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    networks:
      - database
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  postgresql:
    image: arm32v6/postgres:11.2-alpine
    environment:
      POSTGRES_DB_FILE: /run/secrets/db
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - database
    volumes:
      - postgresql_data:/var/lib/postgresql
    configs:
      - source: postgres_init.v1
        target: /docker-entrypoint-initdb.d/postgres_init.sh
        mode: 0777
    secrets:
      - source: postgresql_db.v1
        target: db
      - source: postgresql_user.v1
        target: db_user
      - source: postgresql_password.v1
        target: db_password
      - source: postgresql_grafana_user.v1
        target: postgresql_grafana_user
      - source: postgresql_grafana_password.v1
        target: postgresql_grafana_password
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
configs:
  postgres_init.v1:
    file: ./configs/postgres_init.sh
volumes:
  influxdb_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.19.181.254,v3,nolock,soft,rw
      device: ":/nfs/influxdb"
  postgresql_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.19.181.254,v3,nolock,soft,rw
      device: ":/nfs/postgresql"
secrets:
  postgresql_db.v1:
    file: ./secrets/postgresql_db
  postgresql_user.v1:
    file: ./secrets/postgresql_user
  postgresql_password.v1:
    file: ./secrets/postgresql_password
  postgresql_grafana_user.v1:
    file: ./secrets/postgresql_grafana_user
  postgresql_grafana_password.v1:
    file: ./secrets/postgresql_grafana_password
networks:
  database:
    external: true