version: '3.4'
services:
  grafana:
    image: grafana/grafana
    environment:
      - GF_ANALYTICS_ENABLED=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST__FILE=/run/secrets/grafana_smtp_host
      - GF_SMTP_USER__FILE=/run/secrets/grafana_smtp_user
      - GF_SMTP_PASSWORD__FILE=/run/secrets/grafana_smtp_password
      - GF_SMTP_FROM_ADDRESS__FILE=/run/secrets/grafana_smtp_from_address
    secrets:
      - grafana_smtp_host
      - grafana_smtp_user
      - grafana_smtp_password
      - grafana_smtp_from_address
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
secrets:
  grafana_smtp_host:
    external: true
  grafana_smtp_user:
    external: true
  grafana_smtp_password:
    external: true
  grafana_smtp_from_address:
    external: true
volumes:
  grafana_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.19.181.254,v3,nolock
      device: ":/nfs/grafana"
networks:
  traefik-public:
    external: true

