---
version: '3'
services:
  influx:
    image: influxdb
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_TELEGRAF_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_TELEGRAF_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_DB=telegraf
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
volumes:
  influxdb: