version: '3.4'
services:
  proxy:
    image: mchestr/docker-flow-proxy:arm32v6
    ports:
      - 80:80
      - 443:443
      - 1883:1883
      - 8883:8883
    networks:
      - proxy
    secrets:
      - source: server_cert.v1
        target: cert-server.pem
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
secrets:
  server_cert.v1:
    file: ./secrets/certs/ingress/cert.pem
networks:
  proxy:
    external: true