version: '3.4'
services:
  mosquitto:
    image: eclipse-mosquitto
    networks:
      proxy:
      database:
        aliases:
          - mqtt
    configs:
      - source: config.v4
        target: /mosquitto/config/mosquitto.conf
    secrets:
      - source: server_cert.v1
        target: server.crt
      - source: server_key.v1
        target: server.key
      - source: ca_cert.v1
        target: ca-cert.pem
      - source: passwd.v1
        target: passwd
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.reqMode.1=tcp
        - com.df.port.1=1883
        - com.df.srcPort.1=1883
        - com.df.reqMode.2=tcp
        - com.df.port.2=8883
        - com.df.srcPort.2=8883
secrets:
  ca_cert.v1:
    file: ./secrets/certs/rootCA.crt
  server_cert.v1:
    file: ./secrets/certs/mqtt/server.crt
  server_key.v1:
    file: ./secrets/certs/mqtt/server.key
  passwd.v1:
    file: ./secrets/passwd
configs:
  config.v4:
    file: ./secrets/mosquitto.conf
networks:
  proxy:
    external: true
  database:
    external: true