# Home Assistant configuration
- id: cat_feeder_control
  alias: Write Servo Value to ESP
  trigger:
    platform: state
    entity_id: input_number.servo_control
  action:
    # Replace livingroom with the name you gave the ESP
    - service: esphome.cat_feeder_control_servo
      data_template:
        level: '{{ trigger.to_state.state | int }}'

- id: watering_alert_tts
  alias: Plants Need Water Alert TTS
  trigger:
    platform: numeric_state
    entity_id:
    - sensor.aloe_soil_moisture
    - sensor.clyde_soil_moisture
    - sensor.magda_soil_moisture
    - sensor.parker_soil_moisture
    below: 40
    for: "01:00:00"
  condition:
    condition: or
    conditions:
    - condition: time
      after: "08:00:00"
      before: "22:00:00"
      weekday:
      - sat
      - sun
    - condition: time
      after: "07:00:00"
      before: "09:00:00"
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: time
      after: "17:00:00"
      before: "22:00:00"
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: tts.google_translate_say
    entity_id: media_player.family_room_speaker
    data_template:
      message: "Hey Fam, {{ trigger.to_state.attributes.friendly_name }} needs some water!"

- id: watered_alert_tts
  alias: Plants Been Watered Alert TTS
  trigger:
    platform: numeric_state
    entity_id:
    - sensor.aloe_soil_moisture
    - sensor.clyde_soil_moisture
    - sensor.magda_soil_moisture
    - sensor.parker_soil_moisture
    above: 70
    for: "00:03:00"
  condition:
    condition: or
    conditions:
    - condition: time
      after: "08:00:00"
      before: "22:00:00"
      weekday:
      - sat
      - sun
    - condition: time
      after: "07:00:00"
      before: "09:00:00"
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: time
      after: "17:00:00"
      before: "22:00:00"
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: tts.google_translate_say
    entity_id: media_player.family_room_speaker
    data_template:
      message: "{{ trigger.to_state.attributes.friendly_name }} feels so moist now, thanks!"

- id: watering_alert_notify
  alias: Plants Need Water Alert Notify
  trigger:
    platform: numeric_state
    entity_id:
    - sensor.aloe_soil_moisture
    - sensor.clyde_soil_moisture
    - sensor.magda_soil_moisture
    - sensor.parker_soil_moisture
    below: 40
    for: "01:00:00"
  action:
  - service: notify.notify
    data_template:
      title: "{{ trigger.to_state.attributes.friendly_name }} Needs water!"
      message: "Currently: {{ trigger.to_state.state }}%"

- id: watered_alert_notify
  alias: Plants Been Watered Alert Notify
  trigger:
    platform: numeric_state
    entity_id:
    - sensor.aloe_soil_moisture
    - sensor.clyde_soil_moisture
    - sensor.magda_soil_moisture
    - sensor.parker_soil_moisture
    above: 70
    for: "00:03:00"
  action:
  - service: notify.notify
    data_template:
      title: "{{ trigger.to_state.attributes.friendly_name }} has been watered"
      message: "Currently: {{ trigger.to_state.state }}%"
