version: '3.4'
services:
  traefik:
    image: traefik
    command: --api --docker --docker.swarmMode --docker.domain=traefik --docker.watch
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - traefik-public
    secrets:
      - source: traefik_cert.v2
        target: server-cert.pem
      - source: traefik_key.v2
        target: server-key.pem
    configs:
      - source: traefik_config.v2
        target: /traefik.toml
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        traefik.enable: "true"
        traefik.backend: traefik
        traefik.frontend.rule: PathPrefixStrip:/traefik
        traefik.port: 8080
        traefik.frontend.auth.basic: "${TRAEFIK_DASHBOARD_CREDENTIALS:?err}"
  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    networks:
      - default
      - traefik-public
    volumes:
      - portainer_data:/data
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.backend: portainer
        traefik.frontend.rule: PathPrefixStrip:/portainer
        traefik.port: 9000
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      update_config:
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
configs:
  traefik_config.v2:
    file: ./traefik.toml
secrets:
  traefik_cert.v2:
    file: ./secrets/certs/ingress/server-cert.pem
  traefik_key.v2:
    file: ./secrets/certs/ingress/server-key.pem
volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.19.181.254,v3,nolock
      device: ":/nfs/portainer"
networks:
  traefik-public:
    external: true